Added Docker and docker compose files
ansultan1/task-scheduler pull request #6
Opened 2023-11-07 04:59 UTC by ansultan1

i have containerized the app with docker and docker compose. Now bringing up this application stack is as easy as running the docker compose up command.

2023-11-08 04:35 UTC, OvaisTariq95 requested changes
Good work!

2023-11-08 04:35 UTC, OvaisTariq95 commented on .env
> +SERVER_PORT="8080"
Add newline at the end of file

2023-11-08 04:35 UTC, OvaisTariq95 commented on Dockerfile
> +CMD ["go", "run", "cmd/main.go"]
Add newline at the end of file

2023-11-08 04:35 UTC, OvaisTariq95 commented on docker-compose.yaml
> +    driver: bridge
Add newline at the end of file

2023-11-09 10:17 UTC, ansultan1 commented on docker-compose.yaml
> +    driver: bridge
reslved

2023-11-09 10:17 UTC, merged